; Main.asm file generated by New Project wizard
;
; Created:   Sat Nov 2 2019
; Processor: 80C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================;====================================================================
; VARIABLES
;====================================================================
Cont_Cajas EQU R2
Lmp_Flag EQU R3
Finish_Flag EQU 20h.0
Lamp_cnt1 EQU R4
Lamp_cnt2 EQU R5
Unidades EQU 21h
Decenas EQU 22h
Centenas EQU 23h
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start
      
      org 03h
      clr p3.0
      clr Finish_Flag
      Reti
            
      org 13h
      inc Cont_Cajas
      cjne Cont_Cajas,#200,Keep
      setb Finish_Flag
      reti
      
Keep: mov B,#100
      mov A,Cont_Cajas
      div AB
      mov Centenas, A
      mov A,B
      mov B,#10
      div AB
      mov Decenas,A
      mov Unidades, B
      reti
      
;====================================================================
; CODE SEGMENT
;====================================================================

     org   0100h
Start:	
      mov IE, #00000100B  ;condiciones iniciales desde aquí
      clr Finish_Flag
      mov Lmp_Flag, #0
      mov DPTR, #sevenseg
      mov unidades, #0
      mov decenas, #0
      mov centenas, #0
			  ;hasta aquí
REFRESH1: CALL REFRESH      
      jnb Finish_Flag,REFRESH1
      mov A,#0FFh
      mov P1,A
      mov IE, #00000001B
LED:  call delay
      jb Finish_Flag,LED
      
      org 200h
REFRESH: mov Lamp_cnt1,#5
loop:	 mov Lamp_cnt2,#133
	 djnz Lamp_cnt2,$
	 djnz Lamp_cnt1,loop
	 cjne Lamp_Flag,#0,lamp1
	 mov A,#0FEh
	 mov P1,A
	 mov A, Centenas
	 movc A, @A+DPTR
	 mov P2,A
	 inc Lamp_Flag
	 ret
lamp1:   cjne Lamp_Flag, #1,lamp2
	 mov A, P1
	 rl A
	 mov P1,A
	 mov A, Decenas
	 movc A, @A+DPTR
	 mov P2,A
	 inc Lamp_Flag
	 ret
lamp2	 mov A, P1
	 rl A
	 mov P1, A
	 mov A, Unidades
	 movc A, @A+DPTR
	 mov P2,A
	 mov Lamp_Flag, #0
	 ret
	 
delay:   mov R6, #250
poop	 mov R7, #200
	 djnz R7, $
	 djnz R6, poop
	 cpl P3.0
	 ret

	 
	 ; otra rutina de refrescamiento
	 
;====================================================================
      
org 300h
sevenseg:	db 0FCh,0C0h,0B6h,0E6h,0BAh,6Eh,7Eh,0C4h,0FEh,0CEh

      END
         